#!/bin/bash
#sudo pacman -S nvidia nvidia-utils lib32-nvidia-utils 
# sudo pacman -S nvidia-beta nvidia-utils lib32-nvidia-utils 
# ^^ This worked? Once..?
sudo pacman -S xorg-server xorg-xinit
./unload
./clojure
./plug
./git_setup
./pywal
./WICD

source ~/.bashrc
sudo pacman -S i3 ranger dmenu vim termite compton feh htop cmatrix
yaourt -S bash-pipes

sudo pacman -S xf86-video-nouveau mesa lib32-mesa
