#!/bin/bash
sudo pacman -S nvidia nvidia-utils lib32-nvidia-utils 
# sudo pacman -S nvidia-beta nvidia-utils lib32-nvidia-utils 
# ^^ This worked? Once..?
sudo pacman -S xorg-server xorg-xinit
./unload
./clojure
./plug
./git_setup
./pywal
./WICD

source ~/.bashrc
get vim termite compton feh htop cmatrix
yget bash-pipes

