#!/bin/bash
#sudo pacman -S nvidia nvidia-utils lib32-nvidia-utils 
# sudo pacman -S nvidia-beta nvidia-utils lib32-nvidia-utils 
# ^^ This worked? Once..?

sudo pacman -S xorg-server xorg-xinit
./unload
./setup_clojure
./setup_vim_plugins
./setup_git
./setup_pywal
./setup_WICD

source ~/.bashrc
sudo pacman -S i3 ranger dmenu vim termite compton feh htop cmatrix
yaourt -S bash-pipes

sudo pacman -S xf86-video-nouveau mesa lib32-mesa
sudo pacman -S firefox w3m
sudo yaourt -S polybar
cd ~/projects
mkdir meta >& /dev/null
cd meta
git clone https://github.com/LSaldyt/helper
pip install --user httplib2
pip install --user google-api-python-client

sudo pacman -S steam steam-native-runtime

sudo yaourt -S vim-supertab

./setup_projects

mkdir ~/.i3_logs
