#!/usr/bin/env python3
import sys
import webbrowser
import pyautogui as p
from time import sleep

def main(args):
    p.typewrite(args[0])

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
