#!/bin/bash

# unloads config files into system

cp .config ~/ -a
cp .vimrc ~/
cp .Xmodmap ~
cp .xinitrc ~
cp .Xresources ~
cp .bashrc ~
cp .bash_profile ~
cp .aliases ~
mkdir ~/bin
cp toggle-bar ~/bin
