#!/bin/bash
sudo pacman -S wicd

sudo systemctl disable netctl
sudo systemctl disable netcfg
sudo systemctl disable dhcpcd
sudo systemctl disable networkmanager
sudo gpasswd -a flynn users
sudo systemctl enable wicd.service
sudo systemctl start wicd.service
